language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - yarn install --dev
  - cd ./test/smoke/template
  - yarn install --dev

scripts: 
  - npm test